// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn1K6LUEKSoHco6V2Q_kosyiTurNQS1ds',
    appId: '1:611308201833:android:b5fd107e00ee0faea73ff8',
    messagingSenderId: '611308201833',
    projectId: 'bhumii',
    storageBucket: 'bhumii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8K0qUi2ifSz_pYh7tgcTQ-FBbjSnwW3U',
    appId: '1:611308201833:ios:dfbc0cfca9ea5e59a73ff8',
    messagingSenderId: '611308201833',
    projectId: 'bhumii',
    storageBucket: 'bhumii.appspot.com',
    androidClientId: '611308201833-b4l5c3c8ee7cnd3skue45auc4dr070gv.apps.googleusercontent.com',
    iosClientId: '611308201833-8kh2m6c4sct8pb7il0452f81mavql9l4.apps.googleusercontent.com',
    iosBundleId: 'com.bhumii.app',
  );

}